-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 02:59:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_pst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_pst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_pst` DEFAULT CHARACTER SET utf8 ;
USE `bd_pst` ;

-- -----------------------------------------------------
-- Table `bd_pst`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`usuario` (
  `cedula_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `edad_usuario` VARCHAR(45) NOT NULL,
  `genero_usuario` VARCHAR(45) NOT NULL,
  `permiso_usuario` VARCHAR(45) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `telefono_usuario` VARCHAR(45) NULL,
  `correo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`cedula_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`admin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `cedula_usuario` INT NOT NULL,
  PRIMARY KEY (`id_admin`, `cedula_usuario`),
  INDEX `fk_admin_usuario_idx` (`cedula_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_admin_usuario`
    FOREIGN KEY (`cedula_usuario`)
    REFERENCES `bd_pst`.`usuario` (`cedula_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `cedula_usuario` INT NOT NULL,
  `turno_alumno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_alumno`, `cedula_usuario`),
  INDEX `fk_alumno_usuario1_idx` (`cedula_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_usuario1`
    FOREIGN KEY (`cedula_usuario`)
    REFERENCES `bd_pst`.`usuario` (`cedula_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  `estado_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`tutor` (
  `id_tutor` INT NOT NULL AUTO_INCREMENT,
  `cedula_usuario` INT NOT NULL,
  `tipo_tutor` VARCHAR(45) NOT NULL,
  `categoria_tutor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tutor`, `cedula_usuario`),
  INDEX `fk_tutor_usuario1_idx` (`cedula_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tutor_usuario1`
    FOREIGN KEY (`cedula_usuario`)
    REFERENCES `bd_pst`.`usuario` (`cedula_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`comunidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`comunidad` (
  `id_comunidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_comunidad` VARCHAR(45) NOT NULL,
  `tipo_comunidad` VARCHAR(45) NOT NULL,
  `direccion_comunidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_comunidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`tutor_comunidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`tutor_comunidad` (
  `id_comunidad` INT NOT NULL,
  `nombre_tutor_comunidad` VARCHAR(45) NOT NULL,
  `cedula_tutor` VARCHAR(45) NOT NULL,
  `telefono_tutor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comunidad`),
  CONSTRAINT `fk_tutor_comunidad_comunidad1`
    FOREIGN KEY (`id_comunidad`)
    REFERENCES `bd_pst`.`comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `numero_seccion` VARCHAR(45) NOT NULL,
  `fecha_inicio_semestre` VARCHAR(45) NOT NULL,
  `fecha_cierre_semestre` VARCHAR(45) NOT NULL,
  `estado_semestre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nombre_grupo` VARCHAR(45) NOT NULL,
  `numero_integrantes_grupo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`grupo_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`grupo_alumno` (
  `id_grupo` INT NOT NULL,
  `id_alumno` INT NOT NULL,
  PRIMARY KEY (`id_grupo`, `id_alumno`),
  INDEX `fk_grupo_alumno_alumno1_idx` (`id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_alumno_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `bd_pst`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_alumno_alumno1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `bd_pst`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`semestre` (
  `id_semestre` INT NOT NULL AUTO_INCREMENT,
  `numero_semestre` VARCHAR(45) NOT NULL,
  `fecha_inicio_semestre` VARCHAR(45) NOT NULL,
  `fecha_cierre_semestre` VARCHAR(45) NOT NULL,
  `estado_semestre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_semestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`ano_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`ano_escolar` (
  `id_ano_escolar` INT NOT NULL AUTO_INCREMENT,
  `ano_escolar_nombre` VARCHAR(45) NOT NULL,
  `fase_ano_escolar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ano_escolar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `id_comunidad` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  `id_ano_escolar` INT NOT NULL,
  `id_tutor` INT NOT NULL,
  `titulo_proyecto` VARCHAR(45) NOT NULL,
  `plantamiento_proyecto` VARCHAR(45) NOT NULL,
  `objetivos_generales_proyecto` VARCHAR(45) NOT NULL,
  `objetivos_espesificos_proyecto` VARCHAR(45) NOT NULL,
  `tipo_proyecto` VARCHAR(45) NOT NULL,
  `estado_proyecto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proyecto`, `id_comunidad`, `id_grupo`, `id_ano_escolar`, `id_tutor`),
  INDEX `fk_proyecto_tutor_comunidad1_idx` (`id_comunidad` ASC) VISIBLE,
  INDEX `fk_proyecto_grupo1_idx` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_proyecto_ano_escolar1_idx` (`id_ano_escolar` ASC) VISIBLE,
  INDEX `fk_proyecto_tutor1_idx` (`id_tutor` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_tutor_comunidad1`
    FOREIGN KEY (`id_comunidad`)
    REFERENCES `bd_pst`.`tutor_comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `bd_pst`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_ano_escolar1`
    FOREIGN KEY (`id_ano_escolar`)
    REFERENCES `bd_pst`.`ano_escolar` (`id_ano_escolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_tutor1`
    FOREIGN KEY (`id_tutor`)
    REFERENCES `bd_pst`.`tutor` (`id_tutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pst`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pst`.`inscripcion` (
  `id_inscripcion` INT NOT NULL AUTO_INCREMENT,
  `id_carrera` INT NOT NULL,
  `id_seccion` INT NOT NULL,
  `id_alumno` INT NOT NULL,
  `id_semestre` INT NOT NULL,
  `id_ano_escolar` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_inscripcion`, `id_carrera`, `id_seccion`, `id_alumno`, `id_semestre`, `id_ano_escolar`, `id_proyecto`),
  INDEX `fk_inscripcion_carrera1_idx` (`id_carrera` ASC) VISIBLE,
  INDEX `fk_inscripcion_seccion1_idx` (`id_seccion` ASC) VISIBLE,
  INDEX `fk_inscripcion_alumno1_idx` (`id_alumno` ASC) VISIBLE,
  INDEX `fk_inscripcion_semestre1_idx` (`id_semestre` ASC) VISIBLE,
  INDEX `fk_inscripcion_ano_escolar1_idx` (`id_ano_escolar` ASC) VISIBLE,
  INDEX `fk_inscripcion_proyecto1_idx` (`id_proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_inscripcion_carrera1`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `bd_pst`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_pst`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_alumno1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `bd_pst`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_semestre1`
    FOREIGN KEY (`id_semestre`)
    REFERENCES `bd_pst`.`semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_ano_escolar1`
    FOREIGN KEY (`id_ano_escolar`)
    REFERENCES `bd_pst`.`ano_escolar` (`id_ano_escolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `bd_pst`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
